name: Deploy to GitHub Pages

on:
  # mainブランチにプッシュされた時に自動実行
  push:
    branches: ["main"]
  # GitHubの画面から手動で実行できるようにする設定
  workflow_dispatch:

# GitHub Pagesへのデプロイに必要な権限
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20" # お使いのNodeバージョンに合わせてください

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # ここでビルド成果物のディレクトリ（out）を指定します
          path: './out'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
